apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: shipping-service
  name: shipping-service
  namespace: lab-cnb-00
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - image: us.icr.io/cndb2020/shipping-service-00
        name: shipping-service
        ports:
        - name: app-port
          containerPort: 3001